# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='servers',
        ),
        migrations.AddField(
            model_name='customer',
            name='servers',
            field=models.ManyToManyField(to='Core.Server'),
        ),
    ]
