# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20170823_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Application_Login',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Application_Password',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
