# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20171115_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Citris_URL',
            new_name='Citrux_URL',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='SCPO',
            new_name='Operating_System',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Versions',
            new_name='Product',
        ),
        migrations.AddField(
            model_name='customer',
            name='Cluster',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='Server_Type',
            field=models.CharField(choices=[('physical', 'Physical'), ('vm', 'VM')], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='Status',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Version',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
