# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20171116_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Name',
            new_name='name',
        ),
    ]
