# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_auto_20171116_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cluster',
            field=models.CharField(choices=[('-', '-'), ('yes', 'Yes'), ('no', 'No')], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Server_Type',
            field=models.CharField(choices=[('-', '-'), ('physical', 'Physical'), ('vm', 'VM')], default='-', max_length=10),
        ),
    ]
