# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_auto_20171130_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='Customer_name',
        ),
    ]
