# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-13 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_auto_20171130_1222'),
        ('Core', '0005_auto_20170824_1657'),
    ]

    operations = [
    ]
